Controllers/TableroCMController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Proyecto_sena.Models;

namespace Proyecto_sena.Controllers
{
    public class TableroCMController : Controller
    {
        private readonly proyecto_innubeContext _context;
        private readonly ILogger<TableroCMController> _logger;

        public TableroCMController(ILogger<TableroCMController> logger, proyecto_innubeContext context)
        {
            _logger = logger;
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult MostrarDatos()
        {
            var correo = User.Identity.Name;
            var compañia = this._context.ClienteCompañia.FirstOrDefault(u => u.CorreoElectronicoCompañia == correo);

            ViewBag.compañia = compañia;
            return View();
        }

        [Authorize]
        public IActionResult Editar()
        {
            return View();
        }

        [Authorize]
        public IActionResult EditarCompañia(IFormCollection formCollection)
        {
            string nombre = formCollection["nombre"];
            string telefono = formCollection["telefono"];
            string correo = formCollection["correo"];
            string direccion = formCollection["direccion"];
            string nit_compañia = formCollection["nit_compañia"];

            var correo_original = User.Identity.Name;
            var compañia = this._context.Compañia.FirstOrDefault(u => u.CorreoElectronicoCompañia == correo_original);

            if (!nombre.Equals(""))
            {
                compañia.NombreCompañia = nombre;
            }

            if (!telefono.Equals(""))
            {
                compañia.TelefonoCompañia = telefono;
            }

            if (!correo.Equals(""))
            {
                compañia.CorreoElectronicoCompañia = correo;
            }

            if (!direccion.Equals(""))
            {
                compañia.DireccionCompañia = direccion;
            }

            if (!nit_compañia.Equals(""))
            {
                compañia.NitCompañia = nit_compañia;
            }

            this._context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Views/TableroCM/Editar.cshtml
@model Proyecto_sena.Models.Cliente;

@{
    ViewData["Title"] = "Tablero";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<nav>
    @* <div class="logo">
        <img src="~/img/logo-trans-horizontal_1.png" width="180" height="50">
        </div> *@
    <div class="sesion">
        <img src="/img/usuario.jpeg">
        <span>
            <strong>Bienvenido,</strong><br>compañía
            <i class="fas fa-sign-out-alt"></i>
        </span>
    </div>
</nav>

<section id="dashboard">
    <article class="menu">
        <ul>
            <li class="item"><a href="">Compañía</a></li>
            <li class="item"><a asp-controller="TableroCM" asp-action="Buscar">Búsqueda</a></li>
            <li class="item"><a asp-controller="TableroCM" asp-action="MostrarDatos">Mostrar datos</a></li>
            <li class="item"><a asp-controller="TableroCM" asp-action="Editar">Editar</a></li>
            <li class="item"><a href="">Usuarios</a></li>
        </ul>
    </article>
    <article class="contenido">
        <span>
            Si no desea editar un campo, por favor déjelo en blanco.
        </span>
        <br>

        <form method="POST" asp-action="EditarCompañia">

            @* <input type="hidden" id="IdCliente" name="IdCliente" /> *@
            <div>
                <label asp-for="NombreCliente">Nombre de la compañía</label>
                <input asp-for="NombreCliente" type="text" name="nombre" />
            </div>
            <div>
                <label asp-for="ApellidoCliente">Teléfono</label>
                <input asp-for="ApellidoCliente" type="text" class="sinborde" name="telefono" />
            </div>

            <div>
                <label asp-for="CorreoElectronicoCliente">Correo</label>
                <input asp-for="CorreoElectronicoCliente" type="email" name="correo" />
            </div>

            <div>
                <label asp-for="CorreoElectronicoCliente">Dirección</label>
                <input asp-for="CorreoElectronicoCliente" type="text" name="direccion" />
            </div>

            <div>
                <label asp-for="CorreoElectronicoCliente">NIT de la compañía</label>
                <input asp-for="CorreoElectronicoCliente" type="text" name="nit_compañia" />
            </div>

            <div class="centrarbotonregistro">
                <input type="submit" value="Editar">
            </div>
        </form>

    </article>
</section>

Views/TableroCM/Index.cshtml
@{
    ViewData["Title"] = "TableroCM";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<nav>
    @* <div class="logo">
        <img src="~/img/logo-trans-horizontal_1.png" width="180" height="50">
    </div> *@
    <div class="sesion">
        <img src="/img/usuario.jpeg">
        <span>
            <strong>Bienvenido,</strong><br>usuario
            <i class="fas fa-sign-out-alt"></i>
        </span>
    </div>
</nav>

<section id="dashboard">
    <article class="menu">
        <ul>
            <li class="item"><a href="">Compañías</a></li>
            <li class="item"><a asp-controller="TableroCM" asp-action="Buscar">Búsqueda</a></li>
            <li class="item"><a asp-controller="TableroCM" asp-action="MostrarDatos">Mostrar datos</a></li>
            <li class="item"><a asp-controller="TableroCM" asp-action="Editar">Editar</a></li>
            <li class="item"><a href="">Usuarios</a></li>
        </ul>
    </article>
    <article class="contenido">
        <p>
            Para la compañía cliente sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
    </article>
</section>

Views/TableroCM/MostrarDatos.cshtml
@{
    ViewData["Title"] = "Tablero";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<nav>
    @* <div class="logo">
        <img src="~/img/logo-trans-horizontal_1.png" width="180" height="50">
        </div> *@
    <div class="sesion">
        <img src="/img/usuario.jpeg">
        <span>
            <strong>Bienvenido,</strong><br>usuario
            <i class="fas fa-sign-out-alt"></i>
        </span>
    </div>
</nav>

<section id="dashboard">
    <article class="menu">
        <ul>
            <li class="item"><a href="">Compañía</a></li>
            <li class="item"><a asp-controller="TableroCM" asp-action="Buscar">Búsqueda</a></li>
            <li class="item"><a asp-controller="TableroCM" asp-action="MostrarDatos">Mostrar datos</a></li>
            <li class="item"><a asp-controller="TableroCM" asp-action="Editar">Editar</a></li>
            <li class="item"><a href="">Usuarios</a></li>
        </ul>
    </article>
    <article class="contenido">

        <span>
            Nombre de la compañía: @ViewBag.compañia.NombreCompañia </br>
        </span>

        <span>
            Teléfono de la compañía: @ViewBag.compañia.TelefonoCompañia </br>
        </span>

        <span>
            Correo de la compañía: @ViewBag.compañia.CorreoElectronicoCompañia </br>
        </span>
        
        <span>
            NIT de la compañía: @ViewBag.compañia.NitCompañia </br>
        </span>

        <span>
            Dirección de la compañía: @ViewBag.compañia.NitCompañia </br>
        </span>

        <div>Haga click aquí para cambiar la contraseña</div>

    </article>
</section>