Controllers/TableroController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;

using System.Linq;
using System.Text.Json;
// using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Proyecto_sena.Models;

namespace Proyecto_sena.Controllers
{
    public class TableroController : Controller
    {
        private readonly proyecto_innubeContext _context;
        private readonly ILogger<TableroController> _logger;

        public TableroController(ILogger<TableroController> logger, proyecto_innubeContext context)
        {
            _logger = logger;
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Buscar()
        {
            List<String> lista_datos = new List<string>();

            var oferta_servicios = this._context.OfertaServicios.ToList();
            foreach (var ofer in oferta_servicios)
            {
                var servicio = this._context.ServicioOfrecidos.FirstOrDefault(u => u.IdServicio == ofer.IdServicio);
                lista_datos.Add(servicio.IdServicio);
                lista_datos.Add(servicio.NombreServicio);
                lista_datos.Add(servicio.PrecioServicio.ToString());
                var comp = this._context.Compañia.FirstOrDefault(u => u.IdCompañia == ofer.IdCompañia);
                lista_datos.Add(comp.NombreCompañia);

            }

            ViewBag.longitud = lista_datos.Count();
            ViewBag.lista = lista_datos;
            return View();
        }

        [Authorize]
        public IActionResult MostrarDatos()
        {
            var correo = User.Identity.Name;
            var persona = this._context.Clientes.FirstOrDefault(u => u.CorreoElectronicoCliente == correo);

            ViewBag.persona = persona;
            return View();
        }

        [Authorize]
        public IActionResult Editar()
        {
            var correo = User.Identity.Name;
            var persona = this._context.Clientes.FirstOrDefault(u => u.CorreoElectronicoCliente == correo);

            ViewBag.persona = persona;
            return View();
        }

        [Authorize]
        public IActionResult EditarCliente(IFormCollection formCollection)
        {
            string nombre = formCollection["nombre"];
            string apellido = formCollection["apellido"];
            string correo = formCollection["correo"];

            var correo_original = User.Identity.Name;
            var persona = this._context.Clientes.FirstOrDefault(u => u.CorreoElectronicoCliente == correo_original);

            if (!nombre.Equals(""))
            {
                persona.NombreCliente = nombre;
            }

            if (!apellido.Equals(""))
            {
                persona.ApellidoCliente = apellido;
            }

            if (!correo.Equals(""))
            {
                persona.CorreoElectronicoCliente = correo;
            }

            this._context.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult CogerDatos([FromBody] JsonDocument values)
        {
            List<string> listas_ids = new List<string>();

            Console.WriteLine("Probando");
            JsonElement a = values.RootElement;
            JsonElement ids = a.GetProperty("ids");
            foreach (var c in ids.EnumerateArray())
            {
                if (c.TryGetProperty("id", out JsonElement valor_id))
                {
                    listas_ids.Add(valor_id.GetString());
                }
            }
            TempData["lista_ids"] = listas_ids;

            return RedirectToAction("MostrarServicios", new { ll = listas_ids });
        }

        [Authorize]
        [HttpGet]
        // public IActionResult MostrarServicios([FromBody] JsonDocument values)
        public IActionResult MostrarServicios(List<string> ll)
        {
            List<String> lista_datos = new List<string>();
            // var ids = CogerDatos(values);
            var ids = ll;

            IEnumerable<string> ids2 = ids as IEnumerable<string>;

            foreach (var item in ids)
            {
                var servicio = this._context.ServicioOfrecidos.FirstOrDefault(u => u.IdServicio.Equals(item));
                lista_datos.Add(servicio.IdServicio);
                lista_datos.Add(servicio.NombreServicio);
                lista_datos.Add(servicio.PrecioServicio.ToString());
            }

            ViewBag.longitud = lista_datos.Count();
            ViewBag.lista = lista_datos;

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Tablero/Buscar.cshtml
@{
    ViewData["Title"] = "Buscar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav>
    @* <div class="logo">
        <img src="~/img/logo-trans-horizontal_1.png" width="180" height="50">
        </div> *@
    <div class="sesion">
        <img src="/img/usuario.jpeg">
        <span>
            <strong>Bienvenido,</strong><br>usuario
            <i class="fas fa-sign-out-alt"></i>
        </span>
    </div>
</nav>

<section id="dashboard">

    <article class="menu">
        <ul>
            <li class="item"><a href="">Usuarios</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="Buscar">Búsqueda</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="MostrarDatos">Mostrar datos</a></li>
            <li class="item"><a href="">Usuarios</a></li>
            <li class="item"><a href="">Usuarios</a></li>
        </ul>
    </article>
    <section class="contenido">
        <p>
            Lista de algo
        </p>
        <table id="mitabla">
            <thead>
                <tr>
                    <th class="id_producto">Id producto</th>
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Compañia</th>
                    <th></th>

                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < @ViewBag.longitud; i = i + 4)
                {
                    <tr>
                        <td class="id_producto"> @ViewBag.lista[i]</td>
                        <td> @ViewBag.lista[i + 1]</td>
                        <td> @ViewBag.lista[i +2]</td>
                        <td> @ViewBag.lista[i +3]</td>
                        <td>


                            <button type="button" class="btn btn-outline-secondary boton-sel" data-id=@ViewBag.lista[i]
                            data-bs-toggle="button" autocomplete="off">
                                Seleccionar</button>


                        </td>
                    </tr>
                }
            </tbody>

        </table>
        <br>
        <br>
        <a id="envio-boton" asp-controller="Tablero" asp-action="MostrarServicios" class="btn btn-primary">Enviar
            algo</a>

    </section>
</section>

<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest"></script>

<script>
    const dataTable = new simpleDatatables.DataTable("#mitabla");
    let conjunto_ids = new Set();
    const lista_botones = document.getElementById("mitabla");

    lista_botones.addEventListener("click", (e) => {
        console.log(e.target);
        if (e.target.classList.contains("active") && e.target.classList.contains("btn")) {
            console.log("Tiene la clase que quiero");
            console.log(e.target.dataset.id);
            conjunto_ids.add(e.target.dataset.id);
        }

        if (!e.target.classList.contains("active") && e.target.classList.contains("btn")) {
            console.log("No está la clase");
            console.log(e.target.dataset.id);
            conjunto_ids.delete(e.target.dataset.id);
        }

    });

    const boton = document.getElementById("envio-boton");
    boton.addEventListener("click", (evento) => {
        evento.preventDefault();

        const url = "../Tablero/CogerDatos";

        const lista_ids = { "ids": [] };
        conjunto_ids.forEach(function (value) {
            lista_ids.ids.push({ "id": value })
        });

        try {
            const response = fetch(url, {
                method: "POST",
                body: JSON.stringify(lista_ids),
                headers: {
                    "Content-Type": "application/json;charset=utf-8",
                }
            }).then(console.log(JSON.stringify(lista_ids))).
                then(response => {
                    console.dir(response);
                    console.info(response.url);
                    window.location.replace(response.url);
                }).
                catch(error => console.error(error));
        } catch (e) {
            console.error(e);
        }
    });

</script>

Views/Tablero/Editar.cshtml
@model Proyecto_sena.Models.Cliente;

@{
    ViewData["Title"] = "Tablero";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<nav>
    @* <div class="logo">
        <img src="~/img/logo-trans-horizontal_1.png" width="180" height="50">
        </div> *@
    <div class="sesion">
        <img src="/img/usuario.jpeg">
        <span>
            <strong>Bienvenido,</strong><br>usuario
            <i class="fas fa-sign-out-alt"></i>
        </span>
    </div>
</nav>

<section id="dashboard">
    <article class="menu">
        <ul>
            <li class="item"><a href="">Usuarios</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="Buscar">Búsqueda</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="MostrarDatos">Mostrar datos</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="Editar">Editar</a></li>
            <li class="item"><a href="">Usuarios</a></li>
        </ul>
    </article>
    <article class="contenido">
        <span>
            Si no desea editar un campo, por favor déjelo en blanco.
        </span>
        <br>

        <form method="POST" asp-action="EditarCliente">

            <input type="hidden" id="IdCliente" name="IdCliente" />
            <div>
                <label asp-for="NombreCliente">Nombre</label>
                <input asp-for="NombreCliente" type="text" name="nombre" />
            </div>
            <div>
                <label asp-for="ApellidoCliente">Apellido</label>
                <input asp-for="ApellidoCliente" type="text" class="sinborde" name="apellido" />
            </div>

            <div>
                <label asp-for="CorreoElectronicoCliente">Correo</label>
                <input asp-for="CorreoElectronicoCliente" type="email" name="correo" />
            </div>

            <div class="centrarbotonregistro">
                <input type="submit" value="Editar">
            </div>
        </form>

    </article>
</section>

Views/Tablero/Index.cshtml
@{
    ViewData["Title"] = "Tablero";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<nav>
    @* <div class="logo">
        <img src="~/img/logo-trans-horizontal_1.png" width="180" height="50">
    </div> *@
    <div class="sesion">
        <img src="/img/usuario.jpeg">
        <span>
            <strong>Bienvenido,</strong><br>usuario
            <i class="fas fa-sign-out-alt"></i>
        </span>
    </div>
</nav>

<section id="dashboard">
    <article class="menu">
        <ul>
            <li class="item"><a href="">Usuarios</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="Buscar">Búsqueda</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="MostrarDatos">Mostrar datos</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="Editar">Editar</a></li>
            <li class="item"><a href="">Usuarios</a></li>
        </ul>
    </article>
    <article class="contenido">
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
    </article>
</section>

Views/Tablero/MostrarDatos.cshtml
@{
    ViewData["Title"] = "Tablero";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<nav>
    @* <div class="logo">
        <img src="~/img/logo-trans-horizontal_1.png" width="180" height="50">
        </div> *@
    <div class="sesion">
        <img src="/img/usuario.jpeg">
        <span>
            <strong>Bienvenido,</strong><br>usuario
            <i class="fas fa-sign-out-alt"></i>
        </span>
    </div>
</nav>

<section id="dashboard">
    <article class="menu">
        <ul>
            <li class="item"><a href="">Usuarios</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="Buscar">Búsqueda</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="MostrarDatos">Mostrar datos</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="Editar">Editar</a></li>
            <li class="item"><a href="">Usuarios</a></li>
        </ul>
    </article>
    <article class="contenido">

        <span>
            Nombre de la persona: @ViewBag.persona.NombreCliente </br>
        </span>

        <span>
            Apellido de la persona: @ViewBag.persona.ApellidoCliente </br>
        </span>

        <span>
            Correo de la persona: @ViewBag.persona.CorreoElectronicoCliente </br>
        </span>

        <div>Haga click aquí para cambiar la contraseña</div>

    </article>
</section>

Views/Tablero/MostrarServicios.cshtml
@{
    ViewData["Title"] = "Mostrar servicios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<nav>
    @* <div class="logo">
        <img src="~/img/logo-trans-horizontal_1.png" width="180" height="50">
        </div> *@
    <div class="sesion">
        <img src="/img/usuario.jpeg">
        <span>
            <strong>Bienvenido,</strong><br>usuario
            <i class="fas fa-sign-out-alt"></i>
        </span>
    </div>
</nav>

<section id="dashboard">
    <article class="menu">
        <ul>
            <li class="item"><a href="">Usuarios</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="Buscar">Búsqueda</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="MostrarDatos">Mostrar datos</a></li>
            <li class="item"><a asp-controller="Tablero" asp-action="Editar">Editar</a></li>
            <li class="item"><a href="">Usuarios</a></li>
        </ul>
    </article>
    <article class="contenido">
        <table id="mitabla">
            <thead>
                <tr>
                    <th class="id_producto">Id producto</th>
                    <th>Nombre</th>
                    <th>Precio</th>

                    <th></th>

                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < @ViewBag.longitud; i = i + 3)
                {
                    <tr>
                        <td class="id_producto"> @ViewBag.lista[i]</td>
                        <td> @ViewBag.lista[i + 1]</td>
                        <td> @ViewBag.lista[i +2]</td>

                        <td>

                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </article>
</section>


<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest"></script>

<script>
    const dataTable = new simpleDatatables.DataTable("#mitabla");

</script>