Models/Servicio.cs
using System.ComponentModel.DataAnnotations;

namespace Proyecto_sena.Models
{
    public class Servicio
    {
        [Key]
        public int ServicioID { get; set; }
        public int ClienteInnubeID { get; set; }
        public string Nombre { get; set; }
        public decimal Valor { get; set; }
        public string Descripcion { get; set; }
    }
}

Controllers/ServicioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Proyecto_sena.Data;
using Proyecto_sena.Models;
using System;
using System.Linq;
using System.Text.Json;

namespace Proyecto_sena.Controllers
{
    public class ServicioController : Controller
    {

        private readonly ILogger<ServicioController> _logger;
        private readonly InnubeDbContext DbContext;

        public ServicioController(ILogger<ServicioController> logger, InnubeDbContext dbContext)
        {
            _logger = logger;
            this.DbContext = dbContext;
        }

        public IActionResult MisServiciosOfertados()
        {
            var value = HttpContext.Session.GetString("user");
            ClienteInnube cliente = JsonSerializer.Deserialize<ClienteInnube>(value);
            ViewBag.Usuario = cliente;
            //Antes de guardar valida si el correo existe
            var misServicios = DbContext.Servicio.Where(s => s.ClienteInnubeID == cliente.ClienteInnubeID).ToList();
            return View(misServicios);
        }

        public IActionResult AddServicio(){
            return View();
        }

        [HttpPost]
        public IActionResult RegistrarServicio(IFormCollection formCollection)
        {
            var value = HttpContext.Session.GetString("user");
            ClienteInnube cliente = JsonSerializer.Deserialize<ClienteInnube>(value);
            if(cliente == null){
                ViewBag.Mensaje = "Lo sentimos, su sesión expiro, por favor inicie de nuevo.";
                return View("Mensaje");
            }

            Servicio nuevo = new Servicio();
            nuevo.Nombre = formCollection["nombre"];
            nuevo.Descripcion = formCollection["descripcion"];
            nuevo.Valor =Convert.ToDecimal(formCollection["valor"]);
            nuevo.ClienteInnubeID = cliente.ClienteInnubeID;

            this.DbContext.Servicio.Add(nuevo);

            int vRet = this.DbContext.SaveChanges();
            if (vRet > 0)
            {
                ViewBag.Mensaje = "Servicio registrado exitosamente.";
                return View("Mensaje");
            }

            ViewBag.Mensaje = "Error, no es posible registrar el servicio";
            return View("Mensaje");
        }

    }
}

Views/Servicio/AddServicio.cshtml
@{
    ViewData["Title"] = "AddServicio";
    Layout = "~/Views/Shared/MasterApp.cshtml";
}

<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">
        Adicionar servicio
        <a style="float:right" href="#" class="btn btn-primary btn-circle">+</a>
    </h1>
    <p class="mb-4">Por favor completa la siguiente información.</p>

    <form class="login" method="post" asp-action="RegistrarServicio">
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <label>Nombre del servicio</label>
                    <input type="text" maxlength="70" class="form-control form-control-user" name="nombre">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <label>Valor del servicio</label>
                    <input type="number" maxlength="8" class="form-control form-control-user" name="valor">
                </div>
            </div>
        </div>

         <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <label>Descripción</label>
                    <textarea  maxlength="2000" class="form-control form-control-user" name="descripcion"></textarea>
                </div>
            </div>
        </div>

        <div class="row" style="text-align:center">
            <button type="submit" class="btn btn-primary btn-user btn-block">Guardar</button>
        </div>
    </form>
</div>

Views/Servicio/Mensaje.cshtml
@{
    ViewData["Title"] = "Mensaje";
    Layout = "~/Views/Shared/MasterApp.cshtml";
}

<div class="container-fluid">
	<h3 style="text-align:center">@ViewBag.Mensaje</h3>
</div>

Views/Servicio/MisServiciosOfertados.cshtml
@model List<Servicio>
@{
    ViewData["Title"] = "MisServiciosOfertados";
    Layout = "~/Views/Shared/MasterApp.cshtml";

    ClienteInnube cliente = ViewBag.Usuario;
}

<div class="container-fluid">
    @if (cliente.PersonaJuridica)
    {
        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">
            Mis servicios ofertados
            <a style="float:right" href="@Url.Action("AddServicio","Servicio")" class="btn btn-primary btn-circle">+</a>
        </h1>
        <p class="mb-4">A continuación se listaran los servicios que ud estan vendiendo en la plataforma.</p>

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Mis servicios</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <div class="col-sm-12">
                        @if (Model != null && Model.Count > 0)
                        {
                            <table class="table table-bordered dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                <thead>
                                    <tr role="row">
                                        <th>Nombre</th>
                                        <th>Descripción</th>
                                        <th>Valor</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (Servicio item in Model)
                                    {
                                        <tr>
                                            <td>@item.Nombre</td>
                                            <td>@item.Descripcion</td>
                                            <td>@item.Valor</td>
                                        </tr>

                                    }
                                </tbody>

                            </table>
                        }
                        else
                        {
                            <div>AUN NO TIENE SERVICIOS OFERTADOS.</div>

                        }
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div>Lo sentimos, para publicar tus servicios debes registrarte como empresa.</div>

    }

</div>